{
  final Throwable failure=new RuntimeException();
  context.checking(new Expectations(){
{
      allowing(gradle).getProjectEvaluationBroadcaster();
      will(returnValue(listener));
    }
  }
);
  context.checking(new Expectations(){
{
      one(listener).beforeEvaluate(project);
      one(delegate).evaluate(project);
      will(throwException(failure));
      one(listener).afterEvaluate(with(sameInstance(project)),with(notNullValue(Throwable.class)));
    }
  }
);
  try {
    evaluator.evaluate(project);
    fail();
  }
 catch (  GradleScriptException e) {
    assertThat(e.getOriginalMessage(),equalTo("A problem occurred evaluating " + project + "."));
    assertThat(e.getScriptSource(),sameInstance(scriptSource));
    assertThat(e.getCause(),sameInstance(failure));
  }
}
