{
  final RuntimeException failure=new RuntimeException();
  Bean bean=new Bean(){
    String getFailure(){
      throw failure;
    }
  }
;
  try {
    bean.property("failure");
    fail();
  }
 catch (  Exception e) {
    assertThat(e,sameInstance((Exception)failure));
  }
}
