{
  Throwable cause=locationAwareException(new GradleScriptException("broken",new RuntimeException()));
  Throwable failure=new TaskExecutionException(null,cause);
  DefaultExceptionAnalyser analyser=analyser();
  assertThat(analyser.transform(failure),sameInstance(cause));
}
