{
  try {
    return connection.receive();
  }
 catch (  Exception e) {
    LOG.debug("Problem receiving message to the daemon. Performing 'on failure' operation...");
    onFailure.run();
    throw new GradleException("Unable to receive a message from the daemon.",e);
  }
}
